name = "white_agent"
description = "CBT Therapist Agent"
version = "1.0.0"

url = "" 

defaultInputModes = ["text"]
defaultOutputModes = ["text"]

[capabilities]
streaming = false

[[skills]]
id = "cbt_therapy"
name = "CBT"
description = "Provide CBT-style responses"
tags = ["white"]





[platform]
entrypoint = "src.white_agent.agent:start_white_agent"